kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4

nodes:

  - role: control-plane
    extraMounts:
      - hostPath: /home/martin/lms-project/k8s/lms_data
        containerPath: /lms_data

  - role: worker
    extraPortMappings:

      - containerPort: 30080
        hostPort: 30080
        protocol: TCP

      - containerPort: 80
        hostPort: 80
        protocol: TCP

    extraMounts:
      - hostPath: /home/martin/lms-project/k8s/lms_data
        containerPath: /lms_data
