apiVersion: apps/v1
kind: Deployment

metadata:
  name: lms-backend

spec:
  replicas: 1

  selector:
    matchLabels:
      app: lms-backend

  template:
    metadata:
      labels:
        app: lms-backend

    spec:
      containers:
        - name: backend
          image: lms-backend:latest
          imagePullPolicy: IfNotPresent

          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: DB_HOST

            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: DB_PORT

            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: DB_NAME

            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: DB_USER

            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_PASSWORD

          ports:
            - containerPort: 5000
